name = "dispoflare"
compatibility_date = "2024-03-26"

pages_build_output_dir = "./build/client"

[vars]
# These are runtime environment variables (use secrets via `wrangler secret put` if needed)
# Example:
# CLOUDFLARE_API_TOKEN = ""
# CLOUDFLARE_ACCOUNT_ID = ""
# SENTRY_DSN = ""

[triggers]
crons = ["0 */12 * * *"]
